# Staging 환경 컨테이너 빌드 캐시 PVC 설정
pvc:
  enabled: true
  name: container-builder-pvc
  storageClass: openebs-hostpath
  accessModes:
    - ReadWriteMany
  size: 30Gi          # Staging 은 더 작은 용량
  annotations: {}
  labels:
    environment: staging
