apiVersion: v2
name: plate-cache
version: 0.1.0
description: Plate 컨테이너 캐시 스토리지용 Helm 차트
appVersion: "1.0.0"
keywords:
  - plate
  - cache
  - storage
  - pvc
sources:
  - https://github.com/kimjoongwon/prj-devops
maintainers:
  - name: Plate Team
    email: dev@cocdev.co.kr
