# container-cache chart values
# 환경별 override 로 PVC 용량/StorageClass 조정

pvc:
  enabled: true
  name: container-builder-pvc
  storageClass: "openebs-single-replica"  # openebs-zfs, openebs-hostpath 등 환경에 맞게 조정
  accessModes:
    - ReadWriteOnce
  size: 50Gi
  annotations: {}
  labels: {}
  mountPath: /var/lib/docker  # (참고) 실제 사용 애플리케이션 차트에서 volumeClaimTemplates 또는 PVC mount 로 연결
