apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fe-web.fullname" . }}
  labels:
    {{- include "fe-web.labels" . | nindent 4 }}
  annotations:
    # OpenBao injector annotations
    bao.openbao.org/agent-inject: "true"
    bao.openbao.org/role: "{{ .Values.openbao.role | default "fe-web" }}"
    bao.openbao.org/agent-inject-secret-config: "{{ .Values.openbao.secretPath | default "secret/data/fe-web" }}"
    bao.openbao.org/agent-inject-template-config: |
      {{`{{- with secret "secret/data/fe-web" -}}
      export NAVER_URL="{{ .Data.data.naver_url }}"
      {{- end }}`}}