{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app.kubernetes.io/name: container-cache
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.pvc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.pvc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes: {{ toYaml .Values.pvc.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}
{{- end }}
