{{- if .Values.clusterIssuer.production.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.production.name }}
  labels:
    {{- include "cert-manager-config.labels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.clusterIssuer.production.server }}
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuer.production.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.production.privateKeySecretRef.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
      {{- toYaml .Values.clusterIssuer.production.solvers | nindent 6 }}
{{- end }}