{{- range .Values.global.namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openbao-secrets-manager.serviceAccountName" $ }}
  namespace: {{ . }}
  labels:
    {{- include "openbao-secrets-manager.labels" $ | nindent 4 }}
    app.kubernetes.io/component: service-account
    environment: {{ if contains "prod" . }}production{{ else if contains "stg" . }}staging{{ else }}development{{ end }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if $.Values.serviceAccount.create }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}