apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plate-web.name" . }}     # Pod 가 사용할 ServiceAccount (RBAC / Vault 연동 등 확장용)
  labels:
    {{- include "plate-web.labels" . | nindent 4 }}