apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fe-web.fullname" . }}     # Pod 가 사용할 ServiceAccount (RBAC / Vault 연동 등 확장용)
  labels:
    {{- include "fe-web.labels" . | nindent 4 }}