apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-harbor
  namespace: plate-stg
  labels:
    app.kubernetes.io/name: openbao-harbor
    app.kubernetes.io/component: external-secrets
    environment: staging
spec:
  provider:
    vault:
      server: "https://openbao.cocdev.co.kr"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-token"
          key: "token"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-harbor
  namespace: plate-prod
  labels:
    app.kubernetes.io/name: openbao-harbor
    app.kubernetes.io/component: external-secrets
    environment: production
spec:
  provider:
    vault:
      server: "https://openbao.cocdev.co.kr"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-token"
          key: "token"