apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-secret-reader
  namespace: plate-stg
  labels:
    app.kubernetes.io/name: harbor-secret-reader
    app.kubernetes.io/component: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-secret-reader
  namespace: plate-prod
  labels:
    app.kubernetes.io/name: harbor-secret-reader
    app.kubernetes.io/component: external-secrets