apiVersion: v2
name: plate-server
description: Plate Server 백엔드용 Helm 차트
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - plate
  - server
  - backend
home: https://cocdev.co.kr
sources:
  - https://github.com/kimjoongwon/prj-devops
maintainers:
  - name: Plate Team
    email: dev@cocdev.co.kr
