# Plate API Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "be-server.fullname" . }}
  labels:
    {{- include "be-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}           # External service port
      targetPort: {{ .Values.service.targetPort }} # Container port (backend.port: 3006)
      protocol: TCP
      name: http
  selector:
    {{- include "be-server.selectorLabels" . | nindent 4 }}