# Production 환경 컨테이너 빌드 캐시 PVC 설정
pvc:
  enabled: true
  name: container-builder-pvc
  storageClass: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  size: 50Gi          # Production 용량
  annotations: {}
  labels:
    environment: production
