{{- if .Values.serviceAccount.create -}}
# ServiceAccount 리소스 - Pod가 사용할 서비스 계정 정의
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-web.serviceAccountName" . }}
  labels:
    {{- include "frontend-web.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}